apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2021-05-13T10:54:01Z"
  labels:
    app: fluentd
  name: fluentd
  resourceVersion: "393216"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/fluentd
  uid: c0940f73-14b0-4766-bdcd-12228a33d83e
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
