# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# deployments.apps "nginx-dep" was not valid:
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2021-05-13T13:14:34Z"
  generation: 2
  name: dubizzle-web
  labels: 
     {{- include "dubizzle-assesment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "dubizzle-assesment.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2021-05-15T13:05:55Z"
      creationTimestamp: null
      labels:
        {{- include "dubizzle-assesment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.image.name }}
        imagePullPolicy: Always
        name: nginx
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/nginx/
          name: nginx-log
        - mountPath: /etc/nginx/conf.d/
          name: config-volume
      - env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: {{ .Values.elk.name }}
        - name: FLUENT_ELASTICSEARCH_PORT
          value: {{ .Values.elk.port | quote }}
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: http
        - name: FLUENTD_SYSTEMD_CONF
          value: disable
        - name: FLUENTD_ARGS
          value: -c /etc/fluentd-config/fluentd.conf
        image: k8s.gcr.io/fluentd-gcp:1.30
        imagePullPolicy: IfNotPresent
        name: fluentd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/fluentd-config
          name: cmap-volume
        - mountPath: /var/log/nginx
          name: nginx-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx
        name: config-volume
      - emptyDir: {}
        name: nginx-log
      - configMap:
          defaultMode: 420
          name: fluentd-config
        name: cmap-volume
